name: charitypal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  quickalert: ^1.0.2
  image_picker: ^1.0.4
  timeago: ^3.5.0
  draggable_menu: ^4.4.0
  flutterwave_standard: ^1.0.8
  badges: ^3.1.2
  flutter_timer_countdown: ^1.0.5
  text_area: ^0.0.3
  flutter_quill: ^7.4.15
  flutter_profile_picture: ^2.0.0
  html_editor_enhanced: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - images/Capture.PNG
    - images/Charity.gif
    - images/Charity2.gif
    - images/Charity3.gif
    - images/apps.png
    - images/appsfilled.png
    - images/back.png
    - images/bg2.jpg
    - images/bg3.jpg
    - images/bookmark.png
    - images/bookmarkfilled.png
    - images/ch1.jpg
    - images/ch2.jpg
    - images/ch4.png
    - images/close.png
    - images/comment.png
    - images/comment2.png
    - images/donation.png
    - images/donationfilled.png
    - images/event.png
    - images/eventfilled.png
    - images/fullv2.png
    - images/heart.png
    - images/heartfilled.png
    - images/home.png
    - images/homefilled.png
    - images/like.png
    - images/likef.png
    - images/likefilled.png
    - images/liken.png
    - images/log.PNG
    - images/logblack.PNG
    - images/logob.png
    - images/logoblack.png
    - images/logof.png
    - images/logofull.png
    - images/logout.png
    - images/logowhite.png
    - images/lv2.png
    - images/marker.png
    - images/mega.png
    - images/megafilled.png
    - images/news.png
    - images/noti1.png
    - images/noti3.png
    - images/pin.png
    - images/pin2.png
    - images/settings.png
    - images/settingsfilled.png
    - images/star.png
    - images/tick.png
    - images/user.png
    - images/userfilled.png
