// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkYq4gQXraJR5bMlOUUqYR4CJNspmIsl4',
    appId: '1:354428863181:web:0d0e23f9303c96a6c31f84',
    messagingSenderId: '354428863181',
    projectId: 'my-share-joy',
    authDomain: 'my-share-joy.firebaseapp.com',
    storageBucket: 'my-share-joy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0VJOwa_s6mcduSGFSrMxk4b5e4wrEuc',
    appId: '1:354428863181:android:da8d46d07d0744b9c31f84',
    messagingSenderId: '354428863181',
    projectId: 'my-share-joy',
    storageBucket: 'my-share-joy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrNcB5RBpr_c1cSifL9K3CVB8TNA_MpE',
    appId: '1:354428863181:ios:2f0feeaeb3e54ca8c31f84',
    messagingSenderId: '354428863181',
    projectId: 'my-share-joy',
    storageBucket: 'my-share-joy.appspot.com',
    androidClientId: '354428863181-gtchirf2h1bir57kkq43hhco1snojo07.apps.googleusercontent.com',
    iosClientId: '354428863181-t8atnbh20et6s68nqv1mmnojctmpk002.apps.googleusercontent.com',
    iosBundleId: 'com.example.charitypal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrNcB5RBpr_c1cSifL9K3CVB8TNA_MpE',
    appId: '1:354428863181:ios:038683a857e91b81c31f84',
    messagingSenderId: '354428863181',
    projectId: 'my-share-joy',
    storageBucket: 'my-share-joy.appspot.com',
    androidClientId: '354428863181-gtchirf2h1bir57kkq43hhco1snojo07.apps.googleusercontent.com',
    iosClientId: '354428863181-e8d0ffv90g827ebt6043mbrrjmijtpu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.charitypal.RunnerTests',
  );
}
